### ISSUE TITLE
Error - "Having trouble connecting to the server"

### ISSUE THREAD

**Issue by cpflaume** [watson-developer-cloud/assistant-demo#10]
Hello, 

i was just following the instructions but I am getting the "I'm having trouble connecting to the server, please refresh the page" message in the bot.

Request to http://localhost:3000/api/session fails with {code: 404, x-global-transaction-id: "0e7fa6da5cc0128a2e463b81"}

and http://localhost:3000/api/message with 500.

Any guesses? 
I added my credentials to a .env file like this:

ASSISTANT_URL=https://gateway-fra.watsonplatform.net/assistant/api
ASSISTANT_IAM_APIKEY=xxx (api from the watson assistant service)
ASSISTANT_ID=( added the workspace ID and tried the skill id)

I wonder, where the ASSISTANT_IAM_APIKEY and ASSISTANT_URL are getting picked up, as i cannot find them in code..

Kind regards
Constantin

**Comment by Oliver-I** [comment]
@cpflaume Have you tried using the assistant ID, located in Assistant Settings (see screen shot below)?

Please note you must also add the skill (formerly called workspace) to an assistant to see this information.


![image](https://user-images.githubusercontent.com/24578377/56769237-f19fb400-67f3-11e9-8c21-f44e5640fbf1.png)

![image](https://user-images.githubusercontent.com/24578377/56769483-aafe8980-67f4-11e9-95a9-0cae723118c1.png)

**Comment by Oliver-I** [comment]
@cpflaume Are you now able to connect?

**Comment by cpflaume** [comment]
yes I worked it out. I didn't use the assistant id - going to assistants-> assistant settings -> api details did the trick. 
Thanks for your quick support!
