### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by paulo-leitao** [watson-developer-cloud/assistant-demo#14]
I follow all the instructions to deploy the application to IBM Cloud, but i'm getting the status of 500 (Internal server error). The application runs locally without a problem, but when deployed to the cloud the page dont load any content, only appears the message of the error.
Even when deploying the application without any change in code.

**Comment by Oliver-I** [comment]
@paulo-leitao Have you renamed the .env.example file and entered your API key/credentials in the file?

**Comment by paulo-leitao** [comment]
yes, i did. The credentials are ok, working fine locally.

**Comment by Oliver-I** [comment]
Have you checked the Environment Variables in the app's Runtime? When you click on the app in your dashboard you will see Runtime in the left-hand menu.

Select Runtime then click on Environment Variable option. In the bottom-half of the screen you should see the variables you used in the .env. If you don't see the values, you should add the variables and the corresponding values. Please see screenshot below as an example.

![image](https://user-images.githubusercontent.com/24578377/58854619-2d764500-86e1-11e9-9324-ce9ed304d6d3.png)

**Comment by Oliver-I** [comment]
@paulo-leitao Are you still experiencing this issue?

**Comment by dfalconcognizant** [comment]
I have the same error: Internal error.
