### ISSUE TITLE
Bug: Dialog flows can't reset if user contacts agent

### ISSUE THREAD

**Issue by repjarms** [watson-developer-cloud/assistant-demo#17]
If the user goes through a dialog flow and initiates the "speak to an agent" flow, they are unable to reset the flow by using the control buttons in the left and right sidebar.

This seems to only occur when the user contacts an agent, but occurs even if the user declines to speak to the agent.

Example Flow:

![image](https://user-images.githubusercontent.com/4694018/61303334-5516fd80-a7b5-11e9-8508-1e41770244ef.png)

Any attempt to reset after this point will cause the last message to be repeated indefinitely.

Since the path reset happens by clearing the context and starting at a new node, this is most likely occurring within the Assistant workspace.

**Comment by Oliver-I** [comment]
@repjarms This has been fixed with pull request #18
